config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  require 'rest-client'
  require 'json'

  def index
    # Endpoint para obtener todos los jugadores => http://localhost:3000/api/v1/players
    result = RestClient.get('http://localhost:3001/api/v1/players')
    @players = JSON.parse(result)
    # binding.break reemplaza al raise - hace un stop -
  end

  def show
    # Endpoint para obtener un jugador => http://localhost:3000/api/v1/players
    result = RestClient.get("http://localhost:3001/api/v1/players/#{params[:id]}")
    @player = JSON.parse(result)
  end

  def new
  end

  def create
    result = RestClient.post('http://localhost:3001/api/v1/players', { 'name' => params['name'], 'team' => params['team'] }.to_json,
    {content_type: :json, accept: :json} )

    if result.code == 201
      redirect_to players_path
    else
      render '/players/new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FrontendFutbolapiApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_player_card.html.erb
<%= image_tag "emiliano-martinez.jpg" %>

app/views/players/index.html.erb
<h1>Jugadores de Futbol</h1>
<% @players.each do |player| %>
  <p><%= link_to player["name"], player_path(player["id"]) %></p>
  <p><%= player["team"] %></p>
  <p><%= player["position"] %></p>
  <p><%= player["number"] %></p>

  <img src="<%= player["images_url"] %>" alt="">
<% end %>

app/views/players/new.html.erb
<h1>Jugadores</h1>


<%# <form action="">
  <label for="">name</label>
  <input type="text">
</form> %>

<%= form_with url: players_path, method: :post do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :team %>
  <%= f.text_field :team %>
  <%= f.label :position %>
  <%= f.text_field :position %>
  <%= f.label :images_url %>
  <%= f.text_field :images_url %>
  <%= f.submit %>
<% end %>

app/views/players/show.html.erb
<h1><%= @player["name"]  %></h1>

<p><%= @player["team"] %></p>
<p><%= @player["position"] %></p>
<p><%= @player["number"] %></p>

<img src="<%= @player["images_url"] %>" alt="">